
[general]
	#The material blacklist of this module.
	materialBlacklist = ["brick", "nether_brick", "obsidian", "prismarine", "salt", "dragonstone", "mana_diamond", "mana", "netherite_scrap", "ender_pearl", "ender", "end_stone"]

