version: "3.2"

services:
  minecraft:
    image: itzg/minecraft-server:java8
    volumes:
      #  Uses the modpacks folder in the same folder as the docker-compose.yml for the server files to install
      - ./modpacks:/modpacks:ro
      #  Uses the data folder in the same folder as the docker-compose.yml for config, mods, world etc
      # - ./data:/data
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      # The modpack zip you've downloaded from https://www.curseforge.com/minecraft/modpacks/enigmatica6/files
      CF_SERVER_MOD: /modpacks/Enigmatica6Server-0.3.13.zip
      # Default RAM allocation
      MEMORY: 5G
      OPS: NillerMedDild
    ports:
      - 25565:25565
    restart: unless-stopped
