hiddenTabs = ["enchantment", "worldgen"]
#Range: 1 ~ 4
itemsPerRow = 4
enchantsBlacklist = ["flimflam", "soulBound", "ars_nouveau:reactive"]
showDevData = false
dimensionsBlacklist = [-11]
diyData = false
#Range: 1 ~ 4
itemsPerColumn = 4
disableLootManagerReloading = true

