#Range: 1 ~ 4
itemsPerColumn = 4
#Range: 1 ~ 4
itemsPerRow = 4
diyData = false
showDevData = false
enchantsBlacklist = ["flimflam", "soulBound", "ars_nouveau:reactive"]
hiddenTabs = ["enchantment", "worldgen"]
dimensionsBlacklist = [-11]
disableLootManagerReloading = true

